import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* 强制浏览器每次都重新加载 globals.css，绕过缓存 */}
        <link rel="stylesheet" href={`/globals.css?v=${Date.now()}`} />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
